### PR TITLE
Reset individual and batch score to zero

### PR DESCRIPTION
**Pull request by Nitish145**

### CODE REVIEW

**Comment by dev-ritik** [comment]
Thanks @r1walz for the prompt review, @Nitish145 why can't we just set those earlier values to 0 instead of a new key

**Comment by Nitish145** [comment]
Hey @r1walz @dev-ritik i am just scoring all the scores in a new field. If it works fine i will be deleting the old scorefield..

**Comment by Nitish145** [comment]
If there is some way to test on local machine for the existing users.. it would be of great help

**Comment by dev-ritik** [comment]
Closing this as it would be better if the value is reset from db

**Pull request closed without merging**
